### ISSUE TITLE
Option to export entire contents, not just preview

### ISSUE THREAD

**Issue by SteveEdson** [scottstanfield/markdown-to-json#10]
As mentioned in the title, could there be an option to export the entire posts content?

This way, I can have Jekyll compile my static site, and have this generate JSON for each post, to be used with something like React, Angular or Vue.

**Comment by ssayan** [comment]
I'd really like this. The source mentions that **__content** is removed because it's potentially too large — I'm guessing that's intended to be respectful of filesize, rather than being a technical limitation?

Hoping the maintainers can chime in. I'd be happy to put up a PR, otherwise.

**Comment by scottstanfield** [comment]
No technical limitation. Was meant for summaries. Maybe a flag? A PR would be much appreciated. 

---
Scott Stanfield
scottstanfield@gmail.com

**Comment by ssayan** [comment]
Also would be nice to get some cleaner output when you're only processing one file, rather than maintaining the default format of keys/objects and nesting the content a level deep. That's might be a wider discussion, however.

**Comment by ssayan** [comment]
Looks like this was done before, but not documented. https://github.com/scottstanfield/markdown-to-json/pull/5

I'll add some documentation in a pull request.

**Comment by ssayan** [comment]
See. #11

**Comment by scottstanfield** [comment]
Merged. Thanks guys!
