### ISSUE TITLE
Single file mode

### ISSUE THREAD

**Issue by tscanlin** [scottstanfield/markdown-to-json#24]
Would you accept a PR for single file mode so it doesn't return a files array?

**Comment by scottstanfield** [comment]
Yes!

---
Scott Stanfield
scottstanfield@gmail.com

**Comment by tscanlin** [comment]
I actually need something that can convert the markdown to HTML as well so this isn't going to work for me. Thanks anyway!

**Comment by scottstanfield** [comment]
Oh sure thing. Probably a *lot* more options for Markdown to HTML options out there. 

---
Scott Stanfield
scottstanfield@gmail.com
