### ISSUE TITLE
Feature Request: add a watch mode

### ISSUE THREAD

**Issue by barraponto** [scottstanfield/markdown-to-json#25]
I wanted to have a --watch mode that would trigger the compilation again if any of the files change.

**Comment by scottstanfield** [comment]
Good idea, but there are tons of other single-task tools* that do just this.

For node, try [npm-watch](https://www.npmjs.com/package/npm-watch)

bash/linux: inotifywatch + simple script I wrote:
[iwatch](https://gist.github.com/990be074859f6321d74c5f9d413f92a2)

*DOTADIW:
https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well
