### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by mikaelkaron** [scottstanfield/markdown-to-json#7]
Would it be possible to release a `0.5.0` version?

**Comment by scottstanfield** [comment]
I'm not sure what you mean. Simply update the version number? Or add new features that warrant a version release?

---
Scott Stanfield
scott@vertigo.com

**Comment by mikaelkaron** [comment]
Was thinking of the changes in `master`, or am I somehow not getting the latest when I `npm install markdown-to-json`?

**Comment by scottstanfield** [comment]
Oh I see. That could be the case. I need to let npm know; might be different versions. Will check on that today. 

---
Scott Stanfield
scott@vertigo.com

**Comment by EmmanuelBeziat** [comment]
This don't seem to be solved? I would like to use 0.5.0 too.
Thanks!

**Comment by scottstanfield** [comment]
It's been awhile since I've used `npm` to publish a package. I'll look into this. In the meantime, if someone knew the steps, paste them here and I'll get on it.

**Comment by barraponto** [comment]
Hey @scottstanfield , we should publish an updated package soon. In the meanwhile, I've been using [my own fork](https://www.npmjs.com/package/@barraponto/markdown-to-json) -- but I'd rather roll back and use the main project.

**Comment by scottstanfield** [comment]
Do you mean publish to NPM?

**Comment by barraponto** [comment]
Oh yeah.

**Comment by scottstanfield** [comment]
ok...it's been ages. I'm happy to do it. I'll go look into it, but I kinda forgot. If you know, drop steps here. Otherwise, I'll go look!

**Comment by barraponto** [comment]
well, basically... change the version in "package.json", commit and tag it.
then `npm publish` from the command line. You might have to `npm login` first.

**Comment by scottstanfield** [comment]
right, the `npm login`. I'm also adding you as a contributor to the `package.json`. Thanks for keeping this going!

**Comment by scottstanfield** [comment]
Done! Published as version 0.5.0 to npm registry. Please check it out.

**Comment by barraponto** [comment]
Thanks for the attribution! I'm glad to help.
You may notice my fork has some more changes (using ESLint and some cosmetic functional programming changes). I can make new PRs (but they don't change anything, just makes it more "modern").

**Comment by scottstanfield** [comment]
Can you submit a PR of your fork, and I'll pull it in and bump to version 0.5.1

**Comment by barraponto** [comment]
Ok!
